### ISSUE TITLE
Scratch 01/06 resources

### ISSUE THREAD

**Issue by jrmhaig** [CodeClub/CodeClubUK-Projects#66]
The resources provided for 'Boat Race' (worksheet 6 of Scratch 1) do not correspond to the project guide.

1) The boat is solid red and already has a 'hit' costume
2) There is a ready made maze background that can be used instead of drawing your own

**Comment by CodeClubRik** [comment]
Hi @jrmhaig -- this is now fixed. The online resources project has the changes...

https://scratch.mit.edu/projects/63958014/#editor 

...and the downloadable one will be added to the live site within 24h.

see https://github.com/CodeClub/scratch-curriculum/commit/2d639f5bed7d9d1ecd50788b31af369bbd662db6

**Comment by jrmhaig** [comment]
I see that the BoatRaceResources.sb2 file has the correct boat image but there is also a directory called 'Project Resources' that still contains the wrong one as well as a background.

**Comment by CodeClubRik** [comment]
@jrmhaig that's strange -- my local version is updated to just include the new boat image and no background. @martinpeck is it possible that the resources .zip isn't being rebuilt?
